# Generated by Django 4.0.1 on 2022-01-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ose', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
