# Generated by Django 4.0.1 on 2022-01-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ose', '0004_rename_user_customer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('SW', 'Sportwear'), ('OW', 'Outwear'), ('S', 'Shirt'), ('TS', 'T-shirt')], max_length=2)),
                ('label', models.CharField(choices=[('S', 'secondary'), ('P', 'primary'), ('D', 'danger')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=30)),
                ('UserName', models.CharField(max_length=30)),
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
