# Generated by Django 4.0.1 on 2022-01-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ose', '0006_delete_signup_alter_item_category_alter_item_label_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
