# Generated by Django 4.0.1 on 2022-01-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ose', '0007_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
